export const SHIP_BASE_UPGRADE_SPEED_COST = 5;
export const SHIP_BASE_UPGRADE_CAPACITY_COST = 8;
export const SHIP_SPEED_MAX = 4;
export const SHIP_CAPACITY_MAX = 4;

export const UPGRADE_SPEED_COST_START = 5;
export const UPGRADE_CAPACITY_COST_START = 8;
